"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUBMISSIONS_FAILURE = exports.SUBMISSIONS_SUCCESS = exports.SUBMISSIONS_REQUEST = exports.SUBMISSIONS_RESET = void 0;
exports.SUBMISSIONS_RESET = 'SUBMISSIONS_RESET';
exports.SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST';
exports.SUBMISSIONS_SUCCESS = 'SUBMISSIONS_SUCCESS';
exports.SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE';
