"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUBMISSION_RESET = exports.SUBMISSION_FAILURE = exports.SUBMISSION_SUCCESS = exports.SUBMISSION_SAVE = exports.SUBMISSION_REQUEST = exports.SUBMISSION_CLEAR_ERROR = void 0;
exports.SUBMISSION_CLEAR_ERROR = 'SUBMISSION_CLEAR_ERROR';
exports.SUBMISSION_REQUEST = 'SUBMISSION_REQUEST';
exports.SUBMISSION_SAVE = 'SUBMISSION_SAVE';
exports.SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS';
exports.SUBMISSION_FAILURE = 'SUBMISSION_FAILURE';
exports.SUBMISSION_RESET = 'SUBMISSION_RESET';
